image:
  file: .gitpod.Dockerfile
tasks:
  - init: |
      echo "Gitpod init. Setting up ambianic-edge dev environment."
      pip3 install -e ./src
    command: |
      pyenv global system
      echo "Started ambianic-edge development environment."
      echo "Running ambianic-edge testsuite:"
      python3 -m pytest --cov=ambianic --cov-report=term tests/
  - command: |
      sudo mkdir /opt/ambianic-edge/
      sudo ln -s /workspace/ambianic-edge/ai_models/ /opt/ambianic-edge/ai_models
      pyenv global system
      echo "To run the amgianic-edge server use:"
      echo "python3 -m ambianic"
